//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteManagement.Shared.Resources.Components.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstituteManagement.Shared.Resources.Components.Pages.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage institutes, gyms, teachers, students, and members — all in one place..
        /// </summary>
        internal static string AppIntro {
            get {
                return ResourceManager.GetString("AppIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Our Management Platform .
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools and features for managing educational institutes, teachers, and students..
        /// </summary>
        internal static string GymManagementDesc {
            get {
                return ResourceManager.GetString("GymManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Management .
        /// </summary>
        internal static string GymManagementTitle {
            get {
                return ResourceManager.GetString("GymManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools and features for managing gyms, trainers, and members..
        /// </summary>
        internal static string InstituteManagementDesc {
            get {
                return ResourceManager.GetString("InstituteManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym Management .
        /// </summary>
        internal static string InstituteManagementTitle {
            get {
                return ResourceManager.GetString("InstituteManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as Gym Trainer.
        /// </summary>
        internal static string RegisterAsGymTrainer {
            get {
                return ResourceManager.GetString("RegisterAsGymTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Register as Independent Teacher.
        /// </summary>
        internal static string RegisterAsIndependentTeacher {
            get {
                return ResourceManager.GetString("RegisterAsIndependentTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as Independent Trainer.
        /// </summary>
        internal static string RegisterAsIndependentTrainer {
            get {
                return ResourceManager.GetString("RegisterAsIndependentTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Register as Institute Teacher.
        /// </summary>
        internal static string RegisterAsInstituteTeacher {
            get {
                return ResourceManager.GetString("RegisterAsInstituteTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Register as Member.
        /// </summary>
        internal static string RegisterAsMember {
            get {
                return ResourceManager.GetString("RegisterAsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as Business Owner.
        /// </summary>
        internal static string RegisterAsOwner {
            get {
                return ResourceManager.GetString("RegisterAsOwner", resourceCulture);
            }
        }
    }
}
